services:
  mynofuapi-services:
    build:
      context: .
      dockerfile: Dockerfile
    image: registry.bengkelfajarjaya.com/mynofuapi/stable:1.0.0
    platform: linux/amd64
    ports:
      - "8101:8080"
    restart: unless-stopped
